services:
  gomonitor-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: gomonitor:latest
    container_name: monitor-server
    restart: always
    environment:
      - PUSHOVER_TOKEN=<PUSHOVER_TOKEN>
      - PUSHOVER_USER=<PUSHOVER_USER>
      - DISCORD_WEBHOOK_URL=<DISCORD_WEBHOOK_URL>
    ports:
      - "3000:3000"
    command: ["-mode=server", "-pushover", "-discord"]